---
- hosts: default
  user: vagrant
  sudo: true

  tasks:

    - name: EPEL repository installation
      yum: name=http://dl.fedoraproject.org/pub/epel/beta/7/x86_64/epel-release-7-0.2.noarch.rpm state=present

    - name: YUM package update
      yum: name=* enablerepo=epel state=latest

    - name: YUM package installation
      yum: name={{ item }} enablerepo=epel state=latest
      with_items:
        - git
        - java-1.7.0-openjdk
      notify:
        - firewalld restarted

    - name: Firewall configuration
      shell: firewall-cmd {{ item }}
      with_items:
        - --set-default-zone=public
        - --zone=public --add-masquerade --permanent
        - --zone=public --add-forward-port=port=80:proto=tcp:toport=8080 --permanent
        - --reload

    - name: GitBucket download
      get_url: dest=/vagrant/gitbucket.war url=https://github.com/takezoe/gitbucket/releases/download/2.2.1/gitbucket.war
      sudo: false

    - name: GitBucket launch
      shell: chdir=/vagrant java -jar ./gitbucket.war --port=8080 --gitbucket.home=/vagrant/.gitbucket
      async: 86400
      poll: 0
      sudo: false

  handlers:

    - name: firewalld restarted
      service: enabled=yes name=firewalld state=restarted
