---

- hosts: default
  user: "{{ user }}"
  sudo: true

  vars:
    - epel: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-1.noarch.rpm
    - fwRules:
      - "--set-default-zone=public"
      - "--permanent --add-masquerade"
      - "--permanent --zone=public --add-forward-port=port=80:proto=tcp:toport=8080"
      - "--reload"
    - yums:
      - git
      - java-1.7.0-openjdk

  roles:
    - common
    - gitbucket
