---
- hosts: default
  user: vagrant

  tasks:
    - command: uname -a
      register: system

    - command: cat /etc/redhat-release
      register: release

    - debug: msg="{{ system.stdout }}"
    - debug: msg="{{ release.stdout }}"
