---

- hosts: default
  user: "{{ user }}"
  sudo: true

  vars:
    - epel: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-1.noarch.rpm
    - fwRules:
      - "--set-default-zone=public"
      - "--permanent --zone=public --add-service=ssh"
      - "--permanent --zone=public --add-service=http"
      - "--permanent --zone=public --add-service=https"
      - "--permanent --zone=public --add-service=mysql"
      - "--reload"
    - yums:
      - httpd
      - mysql-server
      - php
      - php-common
      - php-gd
      - php-mysql
      - php-pear
      - php-xml

  roles:
    - common
    - lamp
