---

- hosts: default
  user: "{{ user }}"
  sudo: true

  vars:
    - epel: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-1.noarch.rpm
    - yums:
      - httpd
      - mysql-server
      - php
      - php-common
      - php-gd
      - php-mysql
      - php-pear
      - php-xml

  roles:
    - common
    - lamp
