---

- name: EPEL repository installation
  yum: name={{ epel }} state=present

- name: YUM package update
  yum: name=* enablerepo=epel state=latest

- name: Firewall activating
  service: enabled=yes name=firewalld state=started
  register: firewalld

- name: Firewall configuration
  command: firewall-cmd {{ item }}
  with_items: fwRules
  notify:
    - firewalld restarted
  when: firewalld | success
